Add "zalecenia BHP" to fire exit procedure
jakubnabrdalik/gitkurwa pull request #69
Opened 2020-05-26 20:04 UTC by Bartuz

Hello,

first of all, I'm big fan of the aliases and I use them on a daily basis. 

The one thing I find a bit inconvenient is every time we catch fire in the office, I need to 
1. Unscessufly run `palisiekurwa` command
2. Fix any linter errors that prevents `git commit` via git hooks
3. Sign my commit with gpg which requires 2FA
4. Continue office exit procedure

That's a lot of hustle when the fire is all over the office and everyone needs to wait for me to start office exit procedure.

Saying that I'm proposing to add

```
 --no-gpg-sign --no-verify
```
flags to `palisiekurwa` command

2020-05-26 20:10 UTC, Bartuz commented
I'm not adding these flags to LT/HU/PT-BR as I don't know their BHP.
If you know that propose flags are BHP compliant in their countries, please don't hesitate to kurwa contribute :)

2020-05-26 20:42 UTC, michaldarda approved these changes

2020-05-26 20:44 UTC, michaldarda commented
Did you dig through the git tree to find the original commit and reason the original intention of the author ? Did you analyze the corresponding backend code to find out in which situation are those error raised ? Did you try to reproduce whether those errors can be a part of normal usecase or flow ? Do you have an UML diagram for this ? Did you analyze all potential pitfalls when changing this code ? And the most important, did you discuss the potential changes with your colleagues in team as this is a fragile code that needs lots of consideration ? Please take your time to reason carefully about the code and analyze all potential scenarios, and do not jump to quickly into code changes.

2020-05-26 20:49 UTC, michaldarda requested changes
Did you dig through the git tree to find the original commit and reason the original intention of the author ? Did you analyze the corresponding backend code to find out in which situation are those error raised ? Did you try to reproduce whether those errors can be a part of normal usecase or flow ? Do you have an UML diagram for this ? Did you analyze all potential pitfalls when changing this code ? And the most important, did you discuss the potential changes with your colleagues in team as this is a fragile code that needs lots of consideration ? Please take your time to reason carefully about the code and analyze all potential scenarios, and do not jump to quickly into code changes.

2020-05-26 21:02 UTC, Bartuz commented
@michaldarda these are very valid concerns, thank you for raising them.

I will address them as soon as possible, at the moment I provided UML diagram for it
![download (4)](https://user-images.githubusercontent.com/4388676/82950027-eabe1480-9fa4-11ea-8f74-0d33d1ccd496.jpeg)

2020-05-27 13:32 UTC, michaldarda approved these changes

2020-05-27 13:33 UTC, michaldarda commented
Thanks @Bartuz your intention is clear for me now, that explained a lot :shipit:

2020-05-27 14:18 UTC, Bartuz commented
@michaldarda thank you, kurwa.

2020-05-27 17:07 UTC, jakubnabrdalik commented
@Bartuz this is a valid comment, I have no idea how could we have lived without it.
Thank you sir!

2020-05-27 17:07 UTC, merged

2020-05-28 09:35 UTC, Bartuz commented
>  I have no idea how could we have lived without it

I think it was not reported before due to reverse survivorship bias. The thing was annoying, but no one else reported it, as they couldn't escape the fire quick enough (because of GPG signing and linter errors)

2021-09-10 11:51 UTC, rainqer commented
It is clear that my originally incomplete implementation was a result of insufficient refinement of the task. I will prepare a presentation about it and deliver it to my team at the earliest convenience.